from FrequencyPlotter import FrequencyPlotter
from PasswordGenerator import PasswordGenerator

generator = PasswordGenerator('абвгдеёжзийклмнопрстуфхцчшщъыьэюяАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ')
plotter = FrequencyPlotter(generator)