@startuml
class запуск_программы <<injector>> <<main>> {
}

class система_парсинга {
  - входная_директория: строка
  - выходная_директория: строка
  - обработчик_файлов: FileHandler
  - генератор_scs: ScsGenerator
  - конвертер_scs: SCSConverter
  + запустить()
}

class стандартный_обработчик_файлов {
  - директория: строка
  + загрузить_все_json(): список<объект>
}

class стандартный_конвертер_scs {
  - ключевые_слова: словарь<строка, строка>
  + преобразовать_в_scs(объект: dict): строка
  + определить_концепт(название: строка): строка
}

class стандартный_генератор_scs {
  - директория: строка
  + сохранить_scs(имя_файла: строка, данные: строка): ничего
}

class конфигурация {
  + ВХОДНАЯ_ДИРЕКТОРИЯ: строка
  + ВЫХОДНАЯ_ДИРЕКТОРИЯ: строка
}

запуск_программы ..> система_парсинга: <<create>>
система_парсинга <|.. стандартный_обработчик_файлов
система_парсинга <|.. стандартный_конвертер_scs
система_парсинга <|.. стандартный_генератор_scs
конфигурация <.. система_парсинга: <<use>>
@enduml
