@startuml

class главный_контроллер {
}

interface контроллер_информирования {
  + настроить_уведомления(): настройки_уведомлений
}

class стандартный_контроллер_информирования {
  + настроить_уведомления(): настройки_уведомлений
}

interface уведомление {
  настройки_уведомлений(): настройки_уведомлений
}

class стандартное_уведомление <<data>> {
  + настройки_уведомлений: настройки_уведомлений
}


главный_контроллер "1" o-- "1" контроллер_информирования
контроллер_информирования <|.. стандартный_контроллер_информирования
стандартный_контроллер_информирования  "1" o-- "1" уведомление: - уведомление
уведомление <|.. стандартное_уведомление
@enduml