@startuml

class запуск_программы <<injector>> <<main>> {
}

interface репозиторий_пользователей {
  + получить_пользователя(идентификатор)
  + получить_пользователей()
  + сохранить_пользователя(пользователь : пользователь)
}

interface репозиторий_ресурсов {
  + получить_ресурс(идентификатор)
  + получить_ресурсы()
  + сохранить_ресурс(ресурс : ресурс)
}

interface репозиторий_потреблений {
  + получить_потребление(идентификатор)
  + получить_потребления()
  + сохранить_потребление(потребление : потребление)
}

interface репозиторий_уведомлений {
  + получить_уведомление(идентификатор)
  + получить_уведомления()
  + сохранить_уведомление(уведомление : уведомление)
}

interface репозиторий_отчётов {
  + получить_отчёт(идентификатор)
  + получить_отчёты()
  + сохранить_отчёт(отчёт : отчёт)
}

class стандартный_репозиторий_пользователей {
  - пользователи: список<пользователь>
  + получить_пользователя(идентификатор)
  + получить_пользователей()
  + сохранить_пользователя(пользователь : пользователь)
}

class стандартный_репозиторий_ресурсов {
  - ресурсы: список<ресурс>
  + получить_ресурс(идентификатор)
  + получить_ресурсы()
  + сохранить_ресурс(ресурс : ресурс)
}

class стандартный_репозиторий_потреблений {
  - потребления: список<потребление>
  + получить_потребление(идентификатор)
  + получить_потребления()
  + сохранить_потребление(потребление : потребление)
}

class стандартный_репозиторий_уведомлений {
  - уведомления: список<уведомление>
  + получить_уведомление(идентификатор)
  + получить_уведомления()
  + сохранить_уведомление(уведомление : уведомление)
}

class стандартный_репозиторий_отчётов {
  - отчёты: список<отчёт>
  + получить_отчёт(идентификатор)
  + получить_отчёты()
  + сохранить_отчёт(отчёт : отчёт)
}

interface пользователь {
  + получить_ФИО(): строка
  + получить_email(): строка
  + получить_пароль(): строка
  + получить_роль(): строка
  + получить_отчёты(): список<отчёт>
  + получить_уведомления(): список<уведомление>
  + установить_ФИО(ФИО : строка)
  + установить_email(ФИО : строка)
  + установить_пароль(ФИО : строка)
  + установить_роль(ФИО : строка)
  + установить_отчёты(отчёты: список<отчёт>)
  + установить_уведомления(уведомления: список<уведомление>)
}

interface уведомление {
  + получить_пользователя(): пользователь
  + получить_время(): дата
  + получить_сообщение(): строка
  + установить_пользователя(): пользователь
  + установить_время(): дата
  + установить_сообщение(): строка
}

interface отчёт {
  + получить_пользователя(): пользователь
  + получить_потребление(): потребление
  + получить_дату(): дата
  + получить_описание(): строка
  + установить_пользователя(пользователь : пользователь)
  + установить_потребление(потребление : потребление)
  + установить_дату(дата : дата)
  + установить_описание(описание : строка)
}


interface потребление {
  + получить_период(): дата
  + получить_энергоресурсы(): список<энергоресурс>
  + получить_общие_стоимости_ресурсов(): карта<энергоресурс, общая_стоимость_ресурса>
  + установить_период(период: дата)
  + установить_энергоресурсы(энергоресурсы: список<энергоресурс>)
  + установить_общие_стоимости_ресурсов(общие_стоимости_ресурсов: карта<энергоресурс, общая_стоимость_ресурса>)
}

interface энергоресурс {
  + получить_тип(): строка
  + получить_время(): дата
  + получить_стоимость_за_единицу(): число)
  + получить_тип(тип : строка)
  + получить_время(время : дата)
  + получить_стоимость_за_единицу(стоимость_за_единицу : число)
}

class стандартный_пользователь <<data>> {
  + ФИО: строка
  + email: строка
  + пароль: строка
  + роль: строка
}

class стандартный_энергоресурс <<data>> {
  + тип: строка
  + стоимость_за_единицу: строка
}

class "стандартное_потребление" <<data>> {
  + период: дата
  + общая_стоимость_ресурса: число
}

class стандартное_уведомление <<data>> {
  + пользователь: пользователь
  + сообщение: строка
}

class стандартный_отчет <<data>> {
  + дата: дата
  + пользователь: пользователь
  + описание: строка
}

запуск_программы ..> репозиторий_пользователей: <<create>>
запуск_программы ..> репозиторий_уведомлений: <<create>>
запуск_программы ..> репозиторий_отчётов: <<create>>
запуск_программы ..> репозиторий_потреблений: <<create>>
запуск_программы ..> репозиторий_ресурсов: <<create>>

репозиторий_пользователей <|.. стандартный_репозиторий_пользователей
репозиторий_ресурсов <|.. стандартный_репозиторий_ресурсов
репозиторий_потреблений <|.. стандартный_репозиторий_потреблений
репозиторий_отчётов <|.. стандартный_репозиторий_отчётов
репозиторий_уведомлений <|.. стандартный_репозиторий_уведомлений

стандартный_репозиторий_пользователей "1" o-- "N" пользователь: + пользователи: список<пользователь>
стандартный_репозиторий_уведомлений "1" o-- "N" уведомление: + уведомления: список<уведомление>
стандартный_репозиторий_отчётов "1" o-- "N" отчёт: + отчёты: список<отчёт>
стандартный_репозиторий_потреблений "1" o-- "N" потребление: + потребления: список<потребление>
стандартный_репозиторий_ресурсов "1" o-- "N" энергоресурс: + ресурсы: список<ресурс>

пользователь <|.. стандартный_пользователь
энергоресурс <|.. стандартный_энергоресурс
отчёт <|.. стандартный_отчет
уведомление <|.. стандартное_уведомление
потребление <|.. "стандартное_потребление"

@enduml