@startuml
class запуск_программы <<injector>> <<main>> {
}

class главный_контроллер {
  - приложение: приложение
  - контроллер_пользователей: контроллер_пользователей
  - контроллер_управления_ресурсами: контроллер_управления_ресурсами
  - контроллер_информирования: контроллер_информирования
  + запустить()
}

interface контроллер_пользователей {
  + получить_всех_пользователей(): список<пользователь>
  + получить_всех_жителей_дома(): список<житель_дома>
  + получить_всех_администраторов(): список<администратор>
  + получить_пользователя(идентификатор): пользователь
  + редактировать_пользователя(пользователь : пользователь)
  + создать_пользователя(пользователь : пользователь)
}

interface контроллер_управления_ресурсами {
  + получить_все_энергоресурсы(): список<энергоресурс>
  + получить_энергоресурс(идентификатор): энергоресурс
  + редактировать_энергоресурс(энергоресурс: энергоресурс): энергоресурс
  + получить_все_данные_о_потреблениях(): список<потребление>
  + получить_потребление(идентификатор): потребление
  + редактировать_потребление(потребление : потребление): потребление
  + создать_пользователя(пользователь : пользователь): потребление
}

interface контроллер_информирования {
  + получить_все_уведомления(): список<уведомление>
  + получить_уведомление(идентификатор): уведомление
  + создать_уведомление(уведомление: уведомление): уведомление
  + редактировать_уведомление(уведомление: уведомление): уведомление
  + получить_все_отчёты(): список<отчёт>
  + получить_отчёт(идентификатор): отчёт
  + создать_отчёт(отчёт: отчёт): отчёт
  + редактировать_отчёт(отчёт: отчёт): отчёт
}

interface контроллер_авторизации {
  + аутентифицировать(ФИО, пароль): логика
  + завершить_сессию(идентификатор_сессии): ничего
  + проверить_сессию(идентификатор_сессии): логика
}

class стандартный_контроллер_авторизации {
  - репозиторий_пользователей: репозиторий_пользователей
  + авторизовать_пользователя(ФИО: строка, пароль: строка): логика
}

class стандартный_контроллер_пользователей {
  - репозиторий_пользователей: репозиторий_пользователей
  + получить_всех_жителей_дома(): список<житель_дома>
  + получить_всех_администраторов(): список<администратор>
  + получить_пользователя(идентификатор): пользователь
  + редактировать_пользователя(пользователь : пользователь): пользователь
  + создать_пользователя(пользователь : пользователь): пользователь
}

class стандартный_контроллер_управления_ресурсами {
  - репозиторий_энергоресурсов: репозиторий_энергоресурсов
  - репозиторий_потребления: репозиторий_потребления
  + получить_все_энергоресурсы(): список<энергоресурс>
  + получить_энергоресурс(идентификатор): энергоресурс
  + редактировать_энергоресурс(энергоресурс: энергоресурс): энергоресурс
  + получить_все_данные_о_потреблениях(): список<потребление>
  + получить_потребление(идентификатор): потребление
  + редактировать_потребление(потребление : потребление): потребление
  + создать_пользователя(пользователь : пользователь): потребление
}

class стандартный_контроллер_информирования {
  - репозиторий_уведомлений: репозиторий_уведомлений
  - репозиторий_отчётов: репозиторий_отчётов
  + получить_все_уведомления(): список<уведомление>
  + получить_уведомление(идентификатор): уведомление
  + создать_уведомление(уведомление: уведомление): уведомление
  + редактировать_уведомление(уведомление: уведомление): уведомление
  + получить_все_отчёты(): список<отчёт>
  + получить_отчёт(идентификатор): отчёт
  + создать_отчёт(отчёт: отчёт): отчёт
  + редактировать_отчёт(отчёт: отчёт): отчёт
}

interface репозиторий_пользователей {

}

interface репозиторий_энергоресурсов {

}
interface репозиторий_потребления {

}

interface репозиторий_уведомлений {

}

interface репозиторий_отчётов {

}

запуск_программы  ..> главный_контроллер: <<create>>
запуск_программы  ..> контроллер_пользователей: <<create>>
запуск_программы  ..> контроллер_управления_ресурсами: <<create>>
запуск_программы  ..> контроллер_информирования: <<create>>
запуск_программы  ..> контроллер_авторизации: <<create>>
главный_контроллер "1" o-- "1" контроллер_пользователей
главный_контроллер "1" o-- "1" контроллер_управления_ресурсами
главный_контроллер "1" o-- "1" контроллер_информирования
главный_контроллер "1" o-- "1" контроллер_авторизации
контроллер_пользователей <|.. стандартный_контроллер_пользователей
контроллер_управления_ресурсами <|.. стандартный_контроллер_управления_ресурсами
контроллер_информирования <|.. стандартный_контроллер_информирования
контроллер_авторизации <|.. стандартный_контроллер_авторизации
стандартный_контроллер_пользователей "1" --o "1" репозиторий_пользователей
стандартный_контроллер_управления_ресурсами "1" --o "1" репозиторий_энергоресурсов
стандартный_контроллер_управления_ресурсами "1" --o "1" репозиторий_потребления
стандартный_контроллер_информирования "1" --o "1" репозиторий_уведомлений
стандартный_контроллер_информирования "1" --o "1" репозиторий_отчётов
стандартный_контроллер_авторизации "1" --o "1" репозиторий_пользователей

@enduml