@startuml

class главный_контроллер {
}

interface контроллер_ИИ_анализа {
  + анализировать_данные(данные: список<потребление>): рекомендация
  + прогнозировать_потребление(данные: список<потребление>): прогноз_потребления
}

class стандартный_контроллер_ИИ_анализа {
  + анализировать_данные(данные: список<потребление>): рекомендация
  + прогнозировать_потребление(данные: список<потребление>): прогноз_потребления
}

class deeplearning4j <<library>>{
}

interface контроллер_управления_ресурсами {
}

interface контроллер_информирования {
}

главный_контроллер "1" o-- "1" контроллер_ИИ_анализа: - контроллер_ИИ_анализа
контроллер_ИИ_анализа <|.. стандартный_контроллер_ИИ_анализа
deeplearning4j <|.. стандартный_контроллер_ИИ_анализа
стандартный_контроллер_ИИ_анализа  "1" o-- "1" контроллер_управления_ресурсами: - контроллер_управления_ресурсами
стандартный_контроллер_ИИ_анализа  "1" o-- "1" контроллер_информирования: - контроллер_информирования

@enduml