@startuml

left to right direction

state "Окно раздела Авторизация" as auth   {
    "авторизовать_пользователя(ФИО, пароль)": do / КонтроллерАвторизации
}

state "Окно раздела Пользователи" as users    {
    "получить_всеx_Пользователи()": do / КонтроллерПользователей
}

state "Окно создания пользователя" as create_user {
    "создать_пользователя(пользователя)": do / КонтроллерПользователей
}

state "Окно редактирования пользователя" as edit_user {
    "получить_пользователя(Идентификатор)": do / КонтроллерПользователей
    "редактировать_пользователя(Пользователь)": do / КонтроллерПользователей
}



state "Окно раздела Информирование"   as info {
    "получить_все_уведомления()": do / КонтроллерИнформирования
    "получить_все_отчёты()": do / КонтроллерИнформирования
}

state "Окно создания уведомления" as create_notification {
    "создать_уведомление(Уведомление)": do / КонтроллерИнформирования
}

state "Окно создания отчёта" as create_report {
    "создать_отчёт(Отчёт)": do / КонтроллерИнформирования
}

state "Окно редактирования уведомления" as edit_notification {
    "получить_уведомление(Идентификатор)": do / КонтроллерИнформирования
    "редактировать_уведомление(Уведомление)": do / КонтроллерИнформирования
}

state "Окно редактирования отчёта" as edit_report {
    "получить_отчёт(Идентификатор)": do / КонтроллерИнформирования
    "редактировать_отчёт(Отчёт)": do / КонтроллерИнформирования
}



state "Окно раздела Управления ресурсами" as resources  {
    "получить_все_ресурсы()": do / КонтроллерУправленияРесурсами
    "получить_все_данные_о_потреблениях()": do / КонтроллерУправленияРесурсами
}

state "Окно создания ресурса" as create_resource {
    "создать_ресурс(Ресурс)": do / КонтроллерУправленияРесурсами
}

state "Окно создания потребления" as create_consumption {
    "создать_потребление(Потребление)": do / КонтроллерУправленияРесурсами
}

state "Окно редактирования ресурса" as edit_resource {
    "получить_ресурс(Идентификатор)": do / КонтроллерУправленияРесурсами
    "редактировать_ресурс(Ресурс)": do / КонтроллерУправленияРесурсами
}

state "Окно редактирования потребления" as edit_consumption {
    "получить_потребление(Идентификатор)": do / КонтроллерУправленияРесурсами
    "редактировать_потребление(Потребление)": do / КонтроллерУправленияРесурсами
}

[*] --> auth: Система: старт()
auth --> users: Успешная авторизация
auth <-- auth: Введены неверные данные
users --> info: ГлавноеОкно: перейти_в_Информирование()
info --> users: ГлавноеОкно: перейти_в_Пользователи()
users --> [*]: Вид: выход()
users --> resources: ГлавноеОкно: перейти_в_ресурсы()
resources --> users: ГлавноеОкно: перейти_в_Пользователи()

resources --> info: ГлавноеОкно: перейти_в_информирование()
info --> resources: ГлавноеОкно: перейти_в_ресурсы()

users --> create_user: ГлавноеОкно: создать_пользователя()
users --> edit_user: ГлавноеОкно: редакировать_пользователя()

info --> create_notification: ГлавноеОкно: создать_уведомление()
info --> create_report: ГлавноеОкно: создать_отчёт()
info --> edit_notification: ГлавноеОкно: редактировать_уведомление()
info --> edit_report: ГлавноеОкно: редактировать_отчёт()

resources --> create_resource: ГлавноеОкно: создать_ресурс()
resources --> create_consumption: ГлавноеОкно: создать_потребление()
resources --> edit_resource: ГлавноеОкно: редактировать_ресурс()
resources --> edit_consumption: ГлавноеОкно: редактировать_потребление()

create_user --> users: пользователь создан
edit_user --> users: пользователь отредактирован
create_resource --> resources: ресурс создан
create_consumption --> resources: потребление создано
edit_resource --> resources: ресурс отредактирован
edit_consumption --> resources: потребление отредактировано
create_notification --> info: уведомление создано
create_report --> info: отчёт создан
edit_notification --> info: уведомление отредактировано
edit_report --> info: отчёт отредактирован

@enduml