@startuml

class главный_контроллер {
}

interface контроллер_внешних_сервисов {
  + получить_прогноз_погоды(дата: дата): прогноз_погоды
  + получить_температуру(дата: дата): температура
  + установить_параметры_API(api-ключ: строка, url: строка): ничего
}

class стандартный_контроллер_внешних_сервисов {
  + получить_прогноз_погоды(дата: дата): прогноз_погоды
  + получить_температуру(дата: дата): температура
  + установить_параметры_API(api-ключ: строка, url: строка): ничего
}

class Яндекс.Погода <<API>> {
}

interface рекомендация {
  + получить_прогноз(прогноз: получить_прогноз): получить_прогноз
}

class стандартная_рекомендация <<data>> {
  + рекомендация: рекомендация
}

главный_контроллер "1" o-- "1" контроллер_внешних_сервисов: - контроллер_внешних_сервисов
контроллер_внешних_сервисов <|.. стандартный_контроллер_внешних_сервисов
Яндекс.Погода <|.. стандартный_контроллер_внешних_сервисов
стандартный_контроллер_внешних_сервисов "1" o-- "N" рекомендация: - рекомендация
рекомендация <|.. стандартная_рекомендация
@enduml
