@startuml
left to right direction
class запуск_программы <<main>> <<injector>> {
}

interface главный_контроллер {
}

class приложение <<UI>> <<injector>> {
  # фабрика: фабрика_интерфейса
  - окна: карта<строка, окно>
  + создать_интерфейс(): ничего
  + отрисоавть_интерфейс(): ничего
  + показать_окно(имя: строка): ничего
  + получит_окна(): карта<строка, окно>
}

interface фабрика_интерфейса <<UI>> {
  + создать_окно(): окно
  + создать_кнопку(): кнопка
  + создать_поле(): поле
  + создать_таблицу(): таблица
  + создать_слой(): слой
}

class фабрика_стандартного_интерфейса <<UI>> {
  + создать_окно(): окно
  + создать_кнопку(): кнопка
  + создать_поле(): поле
  + создать_таблицу(): таблица
  + создать_слой(): слой
}


interface окно <<UI>> {
  + добавит_слой(слой: слой): ничего
}

interface кнопка <<UI>> {
  + задать_действие(действие: действие): ничего
}

interface поле <<UI>> {
  + задать_тип(тип: тип_поле): ничего
}

interface таблица <<UI>> {
  + задать_базу(строки: число, столбцы: число): ничего
}

interface слой <<UI>> {
  + задать_тип(тип: тип_слоя): ничего
  + добавить(объект: интерфейсный_объект, x: число, y: число): ничего
}

interface интерфейсный_объект <<UI>> {
  + задать_размеры(длина: число, ширина: число): ничего
  + отрисовать(): ничего
}


запуск_программы  ..> приложение: <<create>>
главный_контроллер "1" o--> "1" приложение
приложение "1" o--> "1" фабрика_интерфейса
фабрика_стандартного_интерфейса --|> фабрика_интерфейса
фабрика_стандартного_интерфейса ..> окно
фабрика_стандартного_интерфейса ..> кнопка
фабрика_стандартного_интерфейса ..> поле
фабрика_стандартного_интерфейса ..> таблица
фабрика_стандартного_интерфейса ..> слой

окно --|> интерфейсный_объект
кнопка --|> интерфейсный_объект
поле --|> интерфейсный_объект
таблица --|> интерфейсный_объект
слой --|> интерфейсный_объект

@enduml